### ISSUE TITLE
Cmake errors in the lab

### ISSUE THREAD

**Issue by n00b0001** [marovira/uvic-animation#1]
There is a Cmake error since atlas is not in the folder it is supposed to be in (there is no atlas anywhere in the project directories at all).

**Comment by n00b0001** [comment]
I just copied atlas v1.1.1 into /lib/atlas/ and it seems to work.

**Comment by marovira** [comment]
@n00b0001 When you cloned the uvic-animation repo, did you do the following?

```
cd /path/to/lab
git submodule init
git submodule update
```

Atlas is references in the repo as a submodule, **not** as a direct copy. So you need to run these commands **before** attempting to build anything with CMake.
